pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/kvelskrishnan/simple-java-maven-app.git']]])
            }
        }
        stage('Build') {
            steps {
             sh 'mvn -B -DskipTests clean package'   
            }
            
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        /*stage('Sonarqube') {
            steps {
             sh 'Publish results to sonarqube'   
            }
            
        }*/
        /*stage('Deploy') {
            steps {
                sh """ scp -r target/my-app-1.0-SNAPSHOT.jar 18.236.137.164@ec2-user:/var/lib """
                
            }
        }*/
    }
}
